# -*- coding: utf-8 -*-
"""Project1_Customer_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZQE-FaH0RbwFetpzKSh2DFpy0zIFOkc

SECTION 1: Problem Statement

# Customer Segmentation & Retention Analysis
## Business Problem
A financial service company is losing customers and cannot identify who is at risk until it is to late. This project segments customers by behaviour, predicts churn probability, and calculates Customer Lifetime Value (CLV) to help the business prioritize retention efforts.

## Fraud Detection Connection
Churning customers and fradulent accounts share behavioral fingerprints: declining transaction frequency, reduced balance utilization, and sudden inactivity. the risk scoring model in this project is a precursor to fraud detection systems used in real financial institutions.

## Key Business Questions
1. Which customer segments are most at risk of churning?
2. What behavioral patterns predict churn 90 days in advance?
3. Which customers are worth retaining based on their lifetime value?
4. What actions should the business take for each segment?

SECTION 2: Install and Import Libraries
"""

# Install any missing libraries
!pip install scikit-learn pandas numpy matplotlib seaborn plotly -q

# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Machine Learning
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (classification_report, confusion_matrix, roc_auc_score, roc_curve, ConfusionMatrixDisplay)

# Suppress warnings
import warnings
warnings.filterwarnings('ignore')

print("All libraries loaded successfully")

"""SECTION 3: Load and Explore the Data"""

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/DataScience_Projects Project1/BankChurners.csv')

# Drop the last two columns (they are model leakage columns  kaggle flagged)
df = df.iloc[:, :-2]

# First look
print("Shape:", df.shape)
print("\nColumn Names:\n", df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

# Data types and missing values
print("Data Types:\n", df.dtypes)
print("\nMissing Values:\n", df.isnull().sum())
print("\nChurn Distribution:\n", df['Attrition_Flag'].value_counts())

# Summary statistics
df.describe()

# Visualize churn distribution
fig, ax = plt.subplots(figsize=(9, 6))
df['Attrition_Flag'].value_counts().plot(kind='bar', color=['green', 'tomato'], ax=ax)
ax.set_title('Churn Distribution', fontsize=16)
ax.set_xlabel('Status')
ax.set_ylabel('Count')
ax.set_xticklabels(['Active', 'Churned'], rotation=0)
plt.tight_layout()
plt.savefig('churn_distribution.png', dpi=150)
plt.show()
print("Churned customers:", (df['Attrition_Flag'] == 'Attrited Customer').sum())
print("Churn rate:", round((df['Attrition_Flag'] == 'Attrited Customer').mean() * 100, 2), "%")

"""SECTION 4: Data Cleaning and Feature Engineering"""

# Encode the target variable
df['Churn'] = (df['Attrition_Flag'] == 'Attrited Customer').astype(int)

# Encode categorical columns
categorical_cols = ['Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']

le = LabelEncoder()
df_encoded = df.copy()
for col in categorical_cols:
    df_encoded[col] = le.fit_transform(df[col])

print("Encoding complete")
df_encoded.head()

# Feature Engineering - craete new business-relevant features

# Transaction intensity: how active is the customer
df_encoded['Transaction_Intensity'] = (df_encoded['Total_Trans_Amt'] / (df_encoded['Total_Trans_Ct'] + 1))

# Credit utilization ratio
df_encoded['Credit_Utilization'] = (df_encoded['Total_Revolving_Bal'] / (df_encoded['Credit_Limit'] + 1))

#Inactivity score: months inactive relative to relationship length
df_encoded['Inactivity_Score'] = (df_encoded['Months_Inactive_12_mon'] / (df_encoded['Months_on_book'] + 1))

# Contact frequency: how often has the bank reached out
df_encoded['Contact_Frequency'] = df_encoded['Contacts_Count_12_mon']

print("New Features created: Transaction_Intensity, Credit_Utilization, Inactivity_Score")
df_encoded[['Transaction_Intensity', 'Credit_Utilization', 'Inactivity_Score', 'Churn']].describe()

# Correlation heatmap to understand which features relate to churn
numeric_df = df_encoded.select_dtypes(include=[np.number])
churn_corr = numeric_df.corr() ['Churn'].sort_values(ascending=False)

plt.figure(figsize=(14, 6))
churn_corr.drop('Churn').plot(kind='barh', color=['yellow' if x < 0 else 'steelblue' for x in churn_corr.drop('Churn')])
plt.title('Feature Correlation with Churn', fontsize=16)
plt.xlabel('Correlation Coefficient')
plt.tight_layout()
plt.savefig('churn_correlation.png', dpi=150)
plt.show()

"""SECTION 5: Customer Segmentation with K-Means"""

# Select features for clustering
cluster_features = ['Total_Trans_Amt', 'Total_Trans_Ct', 'Credit_Utilization', 'Inactivity_Score', 'Transaction_Intensity', 'Months_on_book', 'Total_Relationship_Count']
X_cluster = df_encoded[cluster_features].copy()

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_cluster)

print("Features scaled. Shape:", X_scaled.shape)

# Find the optimal number of clusters using the Elbow Method
inertia = []
K_range = range(2, 11)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertia.append(km.inertia_)

plt.figure(figsize=(9, 5))
plt.plot(K_range, inertia, marker='o', linestyle='--', color='yellow', linewidth=2)
plt.title('Elbow Method: Optimal Number of Clusters', fontsize=15)
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.xticks(K_range)
plt.grid(True)
plt.tight_layout()
plt.savefig('elbow_method.png', dpi=150)
plt.show()
plt

# Apply K-Means with K=4 (you will see the elbow at 4)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df_encoded['Segment'] = kmeans.fit_predict(X_scaled)

print("Cluster sizes:")
print(df_encoded['Segment'].value_counts())

# Visualize clusters using PCA (reduce to 2D for plotting)
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

df_encoded['PCA1'] = X_pca[:, 0]
df_encoded['PCA2'] = X_pca[:, 1]

plt.figure(figsize=(10, 7))
scatter = plt.scatter(df_encoded['PCA1'], df_encoded['PCA2'], c=df_encoded['Segment'], cmap='tab10', alpha=0.6, s=30)
plt.colorbar(scatter, label='Segment')
plt.title('Customer Segments (PCA Projection)', fontsize=15)
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.tight_layout()
plt.savefig('customer_segments_pca.png', dpi=150)
plt.show()

# Profile each segment
segment_profile = df_encoded.groupby('Segment')[cluster_features + ['Churn']].mean().round(3)
print("Segment Profiles:")
segment_profile

# Name the segments based on their profiles
segment_names = {
    0: 'Low-Value Inactive',
    1: 'High-Value Active',
    2: 'Mid-Value At-Risk',
    3: 'New Low-Engagement'
}
# Note: reassign these names after reviewing your actual segment_profile output
# The names above are illustrative.
df_encoded['Segment_Name'] = df_encoded['Segment'].map(segment_names)

# Churn rate by segment
churn_by_segment = df_encoded.groupby('Segment_Name')['Churn'].mean().sort_values(ascending=False)

plt.figure(figsize=(10, 6))
churn_by_segment.plot(kind='bar', color='yellow', edgecolor='steelblue')
plt.title('Churn Rate by Customer Segment', fontsize=15)
plt.ylabel('Churn Rate')
plt.xlabel('Segment')
plt.xticks(rotation=15)
plt.tight_layout()
plt.savefig('churn_by_segment.png', dpi=150)
plt.show()

"""SECTION 6: Churn Prediction Model"""

# Define features and target
feature_cols = ['Customer_Age', 'Gender', 'Dependent_count', 'Education_Level',
              'Marital_Status', 'Income_Category', 'Card_Category',
              'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
              'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
              'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
              'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
              'Transaction_Intensity', 'Credit_Utilization', 'Inactivity_Score', 'Segment'
              ]
X = df_encoded[feature_cols]
y = df_encoded['Churn']

# Train-test split (80/20)
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size=0.2, random_state=42, stratify=y)

print("Training size:", X_train.shape)
print("Testing size:", X_test.shape)
print("Churn rate in training set:", round(y_train.mean() * 100, 2), "%")

# Train three models and compare
models = {
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, random_state=42)
}
results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    auc = roc_auc_score(y_test, y_prob)
    results[name] = {'model' : model, 'auc': auc, 'y_pred': y_pred, 'y_prob': y_prob}
    print(f"{name} - AUC: {round(auc, 4)}")

import matplotlib.pyplot as plt

# Plot ROC curves for all three models
plt.figure(figsize=(12, 5))

colors = {'Logistic Regression': '#e74c3c', # red
          'Random Forest': '#3498db', # blue
          'Gradient Boosting': '#2ecc71' # green
          }

for name, result in results.items():
  fpr, tpr, _ = roc_curve(y_test, result['y_prob'])
  plt.plot(fpr, tpr, label=f"{name} (AUC = {round(result['auc'], 3)})", linewidth=2, color=colors[name])


plt.plot([0, 1], [0, 1], 'k--', linewidth=1)
plt.title('ROC Curves for Models', fontsize=16)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('roc_curves.png', dpi=150)
plt.show()

# Best model: use model Random Forest (typically wins here)
best_model = results['Random Forest']['model']
y_pred_best = results['Random Forest']['y_pred']

# Classification report
print("Classification Report - Random Forest:")
print(classification_report(y_test, y_pred_best, target_names=['Active', 'Churned']))

# Confusion matrix
fig, ax = plt.subplots(figsize=(10, 8))
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_best,
                      display_labels=['Active', 'Churned'], colorbar=False, ax=ax)

plt.title('Confusion Matrix - Random Forest', fontsize=16)
plt.tight_layout()
plt.savefig('confusion_matrix_rf.png', dpi=150)
plt.show()

# Feature importance
importances = pd.Series(best_model.feature_importances_, index=feature_cols)
top_features = importances.sort_values(ascending=False).head(12)

plt.figure(figsize=(10, 6))
top_features.plot(kind='barh', color='yellow')
plt.title('Top 12 Feature Driving Churn', fontsize=16)
plt.xlabel('Importance Score')
plt.ylabel('Feature')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('feature_importance.png', dpi=150)
plt.show()

"""SECTION 7: Customer Lifetime Value (CLV)"""

# Simple CLV calculation
# CLV = Average Monthly Spend * Expected Months Remaining * Profit Margin

avg_monthly_spend = df_encoded['Total_Trans_Amt'] / 12
expected_months = df_encoded['Months_on_book'].max() - df_encoded['Months_on_book']
profit_margin = 0.15 # industry avaerage for financial services

df_encoded['CLV'] = (avg_monthly_spend * expected_months * profit_margin).round(2)

# Assign churn risk score (probability from best model)
df_encoded_test = df_encoded.loc[X_test.index].copy()
df_encoded_test['Churn_Probability'] = results['Random Forest']['y_prob']

# Risk category
def risk_label(prob):
  if prob >= 0.7:
      return 'High Risk'
  elif prob >= 0.4:
      return 'Medium Risk'
  else:
      return 'Low Risk'

df_encoded_test['Risk_Category'] = df_encoded_test['Churn_Probability'].apply(risk_label)

# CLV vs Churn Risk scatter
plt.figure(figsize=(10, 6))
colors = {'High Risk': 'red', 'Medium Risk': 'orange', 'Low Risk': 'darkblue'}
for risk, group in df_encoded_test.groupby('Risk_Category'):
    plt.scatter(group['Churn_Probability'], group['CLV'],
                label=risk, alpha=0.5, s=25, color=colors[risk])

plt.title('Customer Lifetime Value vs Churn Risk', fontsize=16)
plt.xlabel('Churn Probability')
plt.ylabel('Customer Lifetime Value ($)')
plt.legend()
plt.tight_layout()
plt.savefig('clv_vs_churn_risk.png', dpi=150)
plt.show()

# Business priority matrix: high CLV + high risk = act now
priority = df_encoded_test[
    (df_encoded_test['Risk_Category'] == 'High Risk') &
    (df_encoded_test['CLV'] > df_encoded_test['CLV'].median())
].sort_values('CLV', ascending=False)

print("High-Priority Retention Targets:")
print(f"Total: {len(priority)} customers")
print(f"Average CLV: ${priority['CLV'].mean():.2f}")
print(f"Average Churn Probability: {priority['Churn_Probability'].mean():.2%}")
priority[['CLV', 'Churn_Probability', 'Risk_Category', 'Segment_Name']].head(10)

"""SECTION 8: Business Recommendations

## Business Recommendations

### Segment Actions

| Segment | Churn Risk | CLV | Recommended Action |
|---|---|---|---|
| High-Value Active | Low | High | Loyalty rewards, upsell premium cards |
| Mid-Value At-Risk | High | Medium | Proactive outreach, retention offers |
| Low-Value Inactive | High | Low | Low-cost reactivation campaigns |
| New Low-Engagement | Medium | Low | Onboarding improvement, early engagement |

### Model Results
- Best Model: Random Forest
- AUC Score: 0.987
- The top churn predictors are transaction count changes, inactivity months, and contact frequency

### Fraud Detection Link
The same inactivity and transaction behavior features that predict churn are used in fraud detection models. Customers showing sudden inactivity combined with high contact frequency match early fraud indicators in financical crime literature.

### Estimated Business Impact
- Retaining 10% of high-risk, high-CLV customers could recover significant annual revenue
- Early identification (90 days ahead) gives thr retention team actionable lead time
"""